# Generated by Django 5.2.5 on 2025-09-14 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_feedbackmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackMessageSnippet',
            fields=[
            ],
            options={
                'verbose_name': 'Сообщение обратной связи',
                'verbose_name_plural': 'Сообщения обратной связи',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.feedbackmessage',),
        ),
    ]
