# Generated by Django 5.2.5 on 2025-08-31 19:55

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('image', models.URLField(verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Растение',
                'verbose_name_plural': 'Растения',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('title_lead', models.CharField(max_length=300, verbose_name='Подзаголовок')),
                ('slogan', models.CharField(max_length=300, verbose_name='Слоган')),
                ('image', models.URLField(verbose_name='Главное изображение')),
                ('description', wagtail.fields.RichTextField(verbose_name='Описание')),
                ('url', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('project_type', models.CharField(max_length=100, verbose_name='Тип проекта')),
                ('region', models.CharField(max_length=100, verbose_name='Регион')),
                ('style', models.CharField(max_length=200, verbose_name='Стиль')),
                ('area', models.IntegerField(verbose_name='Площадь (м²)')),
                ('start_year', models.IntegerField(verbose_name='Год начала')),
                ('end_year', models.IntegerField(verbose_name='Год окончания')),
                ('plants_total', models.IntegerField(verbose_name='Всего растений')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('type', models.CharField(choices=[('text', 'Текстовый блок'), ('image', 'Изображение'), ('fixed', 'Фиксированный блок'), ('gallery', 'Галерея')], max_length=20, verbose_name='Тип блока')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Подзаголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.URLField(blank=True, verbose_name='Изображение')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('images_json', models.TextField(blank=True, verbose_name='Изображения (JSON)')),
                ('project', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='projects.project')),
            ],
            options={
                'verbose_name': 'Блок контента',
                'verbose_name_plural': 'Блоки контента',
            },
        ),
        migrations.CreateModel(
            name='ProjectFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.CharField(max_length=200, verbose_name='Значение')),
                ('project', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='projects.project')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
        migrations.CreateModel(
            name='ProjectPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.plant', verbose_name='Растение')),
                ('project', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='projects.project')),
            ],
            options={
                'verbose_name': 'Растение проекта',
                'verbose_name_plural': 'Растения проекта',
            },
        ),
    ]
