# Generated by Django 5.2.5 on 2025-09-01 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20250901_0740'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        # First, add the new ForeignKey fields as nullable
        migrations.AddField(
            model_name='plant',
            name='image_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='project',
            name='image_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image', verbose_name='Главное изображение'),
        ),
        migrations.AddField(
            model_name='projectblock',
            name='image_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image', verbose_name='Изображение'),
        ),
        
        # Remove the old URL fields
        migrations.RemoveField(
            model_name='plant',
            name='image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.RemoveField(
            model_name='projectblock',
            name='image',
        ),
        
        # Rename the new fields to the original names
        migrations.RenameField(
            model_name='plant',
            old_name='image_new',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='image_new',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='projectblock',
            old_name='image_new',
            new_name='image',
        ),
    ]
