# Generated by Django 5.2.5 on 2025-09-01 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_galleryimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectblock',
            name='images_json',
        ),
    ]
