# Generated by Django 5.2.5 on 2025-09-06 14:46

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20250901_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='url',
        ),
        migrations.AddField(
            model_name='project',
            name='alias',
            field=models.SlugField(default=1, max_length=200, unique=True, verbose_name='Алиас'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='area',
            field=models.IntegerField(blank=True, null=True, verbose_name='Площадь (м²)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год окончания'),
        ),
        migrations.AlterField(
            model_name='project',
            name='plants_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='Всего растений'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Тип проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='region',
            field=models.CharField(blank=True, max_length=100, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год начала'),
        ),
        migrations.AlterField(
            model_name='project',
            name='style',
            field=models.CharField(blank=True, max_length=200, verbose_name='Стиль'),
        ),
        migrations.AlterField(
            model_name='projectblock',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='projectblock',
            name='type',
            field=models.CharField(blank=True, choices=[('text', 'Текстовый блок'), ('image', 'Изображение'), ('fixed', 'Фиксированный блок'), ('gallery', 'Галерея')], max_length=20, null=True, verbose_name='Тип блока'),
        ),
    ]
