# Generated by Django 5.2.5 on 2025-09-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_project_url_project_alias_alter_project_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='mainpage',
            field=models.BooleanField(default=False, verbose_name='Отображать на главной'),
        ),
    ]
