# Generated by Django 5.2.5 on 2025-11-22 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_mainpage'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GalleryImage',
            new_name='ProjectGalleryImage',
        ),
    ]
