# Generated by Django 5.2.5 on 2025-11-22 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_published'),
        ('projects', '0008_rename_galleryimage_projectgalleryimage'),
    ]

    operations = [
    ]
