# Generated by Django 5.2.5 on 2025-11-26 18:05

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_merge_20251122_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectblock',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Описание'),
        ),
    ]
