# Generated by Django 5.2.5 on 2025-09-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        ('projects', '0007_project_mainpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('lead', models.CharField(blank=True, max_length=500, verbose_name='Пояснение')),
                ('portfolio_projects', models.ManyToManyField(blank=True, limit_choices_to={'mainpage': True}, related_name='in_homepage_portfolio', to='projects.project', verbose_name='Проекты для портфолио')),
            ],
            options={
                'verbose_name': 'Настройки главной страницы',
                'verbose_name_plural': 'Настройки главной страницы',
            },
        ),
    ]
