# Generated by Django 5.2.5 on 2025-09-25 20:00

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_mainpageheroimage'),
        ('people', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('lead', models.CharField(blank=True, max_length=500, verbose_name='Пояснение')),
            ],
            options={
                'verbose_name': 'Настройки страницы About',
                'verbose_name_plural': 'Настройки страницы About',
            },
        ),
        migrations.CreateModel(
            name='AboutPageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('type', models.CharField(blank=True, choices=[('text', 'Текстовый блок'), ('image', 'Изображение'), ('fixed', 'Фиксированный блок'), ('gallery', 'Галерея'), ('persons', 'Персоны')], max_length=20, null=True, verbose_name='Тип блока')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Подзаголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image', verbose_name='Изображение')),
                ('parent', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='pages.aboutpagesettings', verbose_name='Настройки About')),
            ],
            options={
                'verbose_name': 'Блок About',
                'verbose_name_plural': 'Блоки About',
            },
        ),
        migrations.CreateModel(
            name='AboutGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtailimages.image', verbose_name='Изображение')),
                ('block', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='pages.aboutpageblock')),
            ],
            options={
                'verbose_name': 'Изображение галереи About',
                'verbose_name_plural': 'Изображения галереи About',
            },
        ),
        migrations.CreateModel(
            name='AboutBlockPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('person', models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, to='people.person', verbose_name='Персона')),
                ('block', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='pages.aboutpageblock')),
            ],
            options={
                'verbose_name': 'Персона блока',
                'verbose_name_plural': 'Персоны блока',
            },
        ),
    ]
