# Generated by Django 5.2.5 on 2025-09-25 20:11

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_aboutpagesettings_aboutpageblock_aboutgalleryimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpageblock',
            name='text',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Текст'),
        ),
    ]
