# Generated by Django 5.2.5 on 2025-10-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_aboutpageblock_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpagesettings',
            name='lead',
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='title_lead',
            field=models.CharField(blank=True, max_length=500, verbose_name='Подзаголовок'),
        ),
    ]
