# Generated by Django 5.2.5 on 2025-09-25 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.SlugField(unique=True, verbose_name='Алиас')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('role', models.CharField(blank=True, max_length=255, verbose_name='Роль')),
                ('biography', models.TextField(blank=True, verbose_name='Биография')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('portrait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Портрет')),
            ],
            options={
                'verbose_name': 'Персона',
                'verbose_name_plural': 'Персоны',
                'db_table': 'people',
            },
        ),
    ]
