# Generated by Django 5.2.5 on 2025-11-26 19:31

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='biography',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Биография'),
        ),
    ]
