# Generated by Django 5.2.5 on 2025-11-22 10:16

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('title_lead', models.CharField(blank=True, max_length=300, verbose_name='Подзаголовок')),
                ('slogan', models.CharField(blank=True, max_length=300, verbose_name='Слоган')),
                ('alias', models.SlugField(max_length=200, unique=True, verbose_name='Алиас')),
                ('description_short', models.TextField(help_text='Для карточки в списке', verbose_name='Краткое описание')),
                ('description', wagtail.fields.RichTextField(blank=True, help_text='Для детальной страницы', verbose_name='Полное описание')),
                ('link_label', models.CharField(default='Подробнее', help_text="Например: 'Подробнее про разработку концепции'", max_length=100, verbose_name='Текст ссылки')),
                ('service_type', models.CharField(blank=True, max_length=100, verbose_name='Тип услуги')),
                ('mainpage', models.BooleanField(default=False, verbose_name='Отображать на главной')),
                ('active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image', verbose_name='Главное изображение')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('type', models.CharField(blank=True, choices=[('text', 'Текстовый блок'), ('image', 'Изображение'), ('fixed', 'Фиксированный блок'), ('gallery', 'Галерея')], max_length=20, null=True, verbose_name='Тип блока')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Подзаголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image', verbose_name='Изображение')),
                ('service', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='services.service')),
            ],
            options={
                'verbose_name': 'Блок контента',
                'verbose_name_plural': 'Блоки контента',
            },
        ),
        migrations.CreateModel(
            name='ServiceGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('block', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='services.serviceblock')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtailimages.image', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Изображение галереи',
                'verbose_name_plural': 'Изображения галереи',
            },
        ),
        migrations.CreateModel(
            name='ServiceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название группы')),
                ('description', models.TextField(verbose_name='Описание группы')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image', verbose_name='Изображение группы')),
            ],
            options={
                'verbose_name': 'Группа услуг',
                'verbose_name_plural': 'Группы услуг',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ServiceGroupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('group', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='services.servicegroup', verbose_name='Группа')),
                ('service', models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Услуга в группе',
                'verbose_name_plural': 'Услуги в группе',
                'unique_together': {('group', 'service')},
            },
        ),
    ]
