# Generated by Django 5.2.5 on 2025-11-26 18:05

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servicegroup_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceblock',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Описание'),
        ),
    ]
